draw_colors: {
    "cracker": [13, 255, 128],                    # green
    "sugar":   [232, 222, 12],                    # yellow
    "soup":    [255, 101, 0],                     # orange
    "mustard": [217,12, 232],                     # magenta
    "gelatin": [255, 255, 255],                   # white
    "meat":    [0, 104, 255],                     # blue
    "bleach":  [0, 104, 255],                     # blue
    "power_drill_with_grip": [152, 78 , 163],     # violet
    "klt": [232, 222, 12],                        # dark yellow
    "multimeter": [0, 255, 255],                  # Aqua
    "relay": [0, 255, 0],                         # Lime
    "screwdriver": [255, 0, 255],                 # Fuchsia
    "materialbox": [0, 0, 255],                   # Blue
    "hot_glue_gun": [255, 20, 147],               # Deep Pink
    "red_part":          [ 68, 225, 239],         # cyan (inverted real color)
    "yellow_part":       [  8,  74, 255],         # blue (inverted real color)
    "bright_green_part": [252,  84, 255],         # magenta/fuchsia (inverted real color)
    "dark_green_part":   [224, 152, 204],         # rose (inverted real color)
    "purple_part":       [127, 215, 156],         # light bluish green (inverted real color)
    "magenta_part":      [ 49, 185, 125],         # dark bluish green (inverted real color)
}
